### ISSUE TITLE
Error installing magnum-plugins on Mac OS X 10.14.5 Mojave

### ISSUE THREAD

**Issue by IanBullard** [mosra/homebrew-magnum#2]
Using brew, the following output is shown while trying to "brew install magnum-plugins":

==> Installing magnum-plugins from mosra/magnum
==> Downloading https://github.com/mosra/magnum-plugins/archive/v2019.01.tar.gz
Already downloaded: /Users/ibullard/Library/Caches/Homebrew/downloads/53509e3a2990a2916b25166b7b9f9bd97ccf6694e94eab4248ef7a54732757bd--magnum-plugins-2019.01.tar.gz
==> mkdir build
==> cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mag
==> cmake --build .
Last 15 lines from /Users/ibullard/Library/Logs/Homebrew/magnum-plugins/03.cmake:
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:888:29: note: in instantiation of function template specialization 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>::operator basic_string_view<std::__1::basic_string_view<char, std::__1::char_traits<char> >, 0>' requested here
        {__self_view __sv = __t; return assign(__sv);}
                            ^
/tmp/magnum-plugins-20190626-49516-66ydmn/magnum-plugins-2019.01/src/MagnumExternal/TinyGltf/tiny_gltf.h:1924:12: note: in instantiation of function template specialization 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>, void>' requested here
    (*ret) = it.value();
           ^
1 error generated.
make[2]: *** [src/MagnumPlugins/TinyGltfImporter/CMakeFiles/TinyGltfImporter.dir/TinyGltfImporter.cpp.o] Error 1
make[1]: *** [src/MagnumPlugins/TinyGltfImporter/CMakeFiles/TinyGltfImporter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Linking CXX shared module StbImageImporter.so
[ 93%] Built target StbImageImporter
[ 95%] Linking CXX shared library libMagnumOpenDdl.dylib
[ 95%] Built target MagnumOpenDdl
make: *** [all] Error 2

**Comment by mosra** [comment]
Hi! This is a known issue with 2019.01 (see mosra/magnum-plugins#54), it's been fixed in master since and so I suggest you to install a HEAD version instead -- you need to install HEAD of all the packages though, in this order:

```sh
brew install --HEAD mosra/magnum/corrade
brew install --HEAD mosra/magnum/magnum
brew install --HEAD mosra/magnum/magnum-plugins
# and similarly extras/examples/integration/bindings as well, if you need them
```

You might need to `uninstall` or `reinstall` instead, I always forget what's the correct command ;)

**Comment by IanBullard** [comment]
That worked, thank you!
