### ISSUE TITLE
brew error on macos

### ISSUE THREAD

**Issue by ghost** [mosra/homebrew-magnum#5]
Dear Team,

[ 82%] Linking CXX shared module ../../../Release/lib/magnum/importers/StbImageImporter.so
[ 82%] Built target StbImageImporter
make: *** [all] Error 2

thanks

**Comment by mosra** [comment]
Hi, sorry, but this doesn't show the actual error. Can you please search the logs for a line that contains `error` in it and post it here?

I have some pending TODOs for Homebrew packages so I'll be checking this at some point anyway, but if you tell me what the error is it'll get solved faster. Thank you! :+1:

**Comment by mosra** [comment]
Huh, a zombie issue :ghost:
